mmult:
	gcc -g -Wall -O3 -o mmult.x code/mmult.c

trape:
	gcc -g -Wall -O3 -o trape.x code/trape.c -lm

rk4:
	gcc -g -Wall -O3 -o rk4.x code/rk4.c

mmult_mpi:
	mpicc -g -Wall -O3 -o mmult_mpi.x code/mmult_mpi.c

trape_mpi:
	mpicc -g -Wall -O3 -o trape_mpi.x code/trape_mpi.c -lm

rk4_mpi:
	mpicc -g -Wall -O3 -o rk4_mpi.x code/rk4_mpi.c
