mmult.x: code/mmult.c
	gcc -g -Wall -o mmult.x code/mmult.c

rect.x: code/rect.c
	gcc -g -Wall -o rect.x code/rect.c -lm

rk3_8.x: code/rk3_8.c
	gcc -g -Wall -o rk3_8.x code/rk3_8.c

p_mmult.x: code/p_mmult.c 
	gcc -g -Wall -o p_mmult.x code/p_mmult.c -lpthread

p_rect.x: code/p_rect.c 
	gcc -g -Wall -o p_rect.x code/p_rect.c -lm -lpthread

p_rk3_8.x: code/p_rk3_8.c 
	gcc -g -Wall -o p_rk3_8.x code/p_rk3_8.c -lpthread
